### ISSUE TITLE
DV Options not showing

### ISSUE THREAD

**Issue by RattyDAVE** [0xAF/openwebrxplus-softmbe-docker#1]
Hi,

Thank you for this build it is fantastic!

I have have a problem that that the Digital Voice modes do not appear. I am using the slechev/openwebrxplus-softmbe container.

![image](https://github.com/0xAF/openwebrxplus-softmbe-docker/assets/9049822/5f30fe9a-ced1-408e-9dfc-a3a5bfbb746d)

Should they be as options? Have I misunderstood?

Thanks

Dave

**Comment by 0xAF** [comment]
Which version you are using?
Try pulling the latest version.
I just tested with the 2023-08-02 (which is currently the latest) and everything seems to be fine.

Note:
Another thing to check is "[Settings]/[Demodulation and decoding]/Codecserver address"
Make sure it's empty and nothing is written in the field.

**Comment by RattyDAVE** [comment]
Still no. :-(

So just for testing I am using using this command line WITHOUT the external volumes so using your container defaults.

This is on a Raspberry Pi 4 8GB

```
docker run -d --name openwebrx --device /dev/bus/usb -p 8073:8073 --tmpfs=/tmp/openwebrx  slechev/openwebrxplus-softmbe:2023-08-02

docker exec -it openwebrx python3 /opt/openwebrx/openwebrx.py admin adduser admin
```

So without changing any options I have in the panel.

![image](https://github.com/0xAF/openwebrxplus-softmbe-docker/assets/9049822/21ee50fb-595d-43a0-9610-882230d39a5e)

And in the options:

![image](https://github.com/0xAF/openwebrxplus-softmbe-docker/assets/9049822/5d5868e3-b2a6-49db-afbc-d1a60d96589c)

Any ideas?

If you want more information just ask. Also if you want access to the options or ssh access to the Pi just shout.

**Comment by RattyDAVE** [comment]
I have done some digging and found in the logs:

```
[services.d] starting services
Hello, I'm the codecserver.
now scanning for modules...
registering new driver: "ambe3k"
dlopen() failed: /usr/local/lib/codecserver/libsoftmbe.so: cannot open shared object file: No such file or directory
loading devices from configuration...
unable to load device: driver "softmbe" not available
[services.d] done.
```

**Comment by 0xAF** [comment]
give me `uname -m` from the host system (rpi4)?

**Comment by RattyDAVE** [comment]
```
root@radiopi:/home/pi# uname -m
aarch64
```

If needed I can swap from 64bit to 32bit. ( I have the 8gb)

**Comment by 0xAF** [comment]
Ohh... sorry for the late reply.. I had some work lately.
Have you found a solution?
If not, I would like to get some access to the system.
This way it will be a lot faster to find the problem.

**Comment by RattyDAVE** [comment]
I have been investigating but cant get to the bottom of it. 
I will email you now with the details.

**Comment by 0xAF** [comment]
i found the problem... will fix it soon and let you know here.
the image have a x86 specific file linking for the softmbe library.

**Comment by 0xAF** [comment]
the image in docker hub is fixed. please report after testing.

**Comment by RattyDAVE** [comment]
Not updated yet on Docker hub.

```
root@radiopi:/home/pi#  docker pull slechev/openwebrxplus-softmbe:latest
latest: Pulling from slechev/openwebrxplus-softmbe
Digest: sha256:74c91ae5b1d585d06764d2192873362fe239e4592e80badfb62aca625d660fd4
Status: Image is up to date for slechev/openwebrxplus-softmbe:latest
docker.io/slechev/openwebrxplus-softmbe:latest
```

**Comment by RattyDAVE** [comment]
OH YES.... 

All working!

**Comment by RattyDAVE** [comment]
I am guessing you jumped on my machine and updated!

**Comment by 0xAF** [comment]
yeah, i pulled the latest to test, but did not updated your container. i used e temporary container.
change the passwords on your machine.
i'm closing the issue now. thanks for the report.

**Comment by RattyDAVE** [comment]
Not a prob! Thanks!
